version: '3.7'

volumes:
  tfgpu_jl_ipynb:
  tfgpu_jl_data:
  tfgpu_jl_lib:

services:
  tfgpu_jl:
    image: d1egoprog/tensorflow-gpu-jupyter:2.9.3-lab
    ports:
      - "9988:8888"
    volumes:
      #- tfgpu_jl_lib:/home/jupyter/.local/share/jupyter/runtime
      - tfgpu_jl_data:/home/jupyter/data
      - tfgpu_jl_ipynb:/home/jupyter/notebooks
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    restart: always
